### ISSUE TITLE
code problems

### ISSUE THREAD

**Issue by SaintLogos1234** [yulu0724/EmbeddingDistillation#1]
I encountered the following problems while running the program you provided：
```
[```
Learn Rate  	1.0e-05
Epochs  	02001
Log Path 	None
Network 	 resnet18
Data Set 	 car
Batch Size  	 32
Num-Instance  	 8
Embedded Dimension 	 512
Loss Function 	triplet
Number of Neighbour 	16
Alpha 	 40
Begin to fine tune BN-inception Network
########################################
/home/xieyangyang/Downloads/EmbeddingDistillation-master_1/models/resnet.py:49: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.feat.weight, mode='fan_out')
/home/xieyangyang/Downloads/EmbeddingDistillation-master_1/models/resnet.py:50: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat.bias, 0)
/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torchvision.models.resnet.ResNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "train_distillation.py", line 231, in <module>
    main(parser.parse_args())
  File "train_distillation.py", line 40, in main
    model_T = torch.load('checkpoints/car_Tmodel.pkl')
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 508, in persistent_load
    data_type(size), location)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 104, in default_restore_location
    result = fn(storage, location)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 75, in _cuda_deserialize
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = torch.load(args.r)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'checkpoints/car_triplet_dis_resnet18_resnet101_relative_0.10_1e-05/0_model.pkl'
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = torch.load(args.r)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'checkpoints/car_triplet_dis_resnet18_resnet101_relative_0.10_1e-05/2000_model.pkl'
](url)
```
```
I add two files to  checkpoints/car_triplet_dis_resnet18_resnet101_relative_0.10_1e-05, But the following error occurred：
```
```
[Learn Rate  	1.0e-05
Epochs  	02001
Log Path 	None
Network 	 resnet18
Data Set 	 car
Batch Size  	 32
Num-Instance  	 8
Embedded Dimension 	 512
Loss Function 	triplet
Number of Neighbour 	16
Alpha 	 40
Begin to fine tune BN-inception Network
########################################
/home/xieyangyang/Downloads/EmbeddingDistillation-master_1/models/resnet.py:49: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.feat.weight, mode='fan_out')
/home/xieyangyang/Downloads/EmbeddingDistillation-master_1/models/resnet.py:50: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat.bias, 0)
/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torchvision.models.resnet.ResNet' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py:425: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "train_distillation.py", line 231, in <module>
    main(parser.parse_args())
  File "train_distillation.py", line 40, in main
    model_T = torch.load('checkpoints/car_Tmodel.pkl')
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 508, in persistent_load
    data_type(size), location)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 104, in default_restore_location
    result = fn(storage, location)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 75, in _cuda_deserialize
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = torch.load(args.r)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    model = torch.load(args.r)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/xieyangyang/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError](url)
```
what can I do?

```

**Comment by SaintLogos1234** [comment]
My pytorch version is 0.4.1, my computer system is Ubuntu16.04, my GPU is 1080Ti

**Comment by yulu0724** [comment]
Please follow the requirement I listed in read-me and use the correct pytorch version.
